//! Golden tests for PES parsing against files generated by pyembroidery.
//!
//! Fixtures in `tests/fixtures/pes` were produced with pyembroidery's
//! PesWriter. `raw_expected.json` was dumped by replicating the byte-level
//! logic of PecReader.read_pec (no post-processing) over the same bytes, so
//! our parser output must match it exactly: same command list, same
//! accumulated absolute positions.

use pdf_collection_viewer_lib::embroidery::StitchType;
use pdf_collection_viewer_lib::embroidery::pes::parse_pes;
use serde_json::Value;

fn fixture_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/pes")
}

/// Accumulates reference deltas into absolute positions with our StitchType.
fn reference_commands(v: &Value) -> Vec<(i32, i32, StitchType)> {
    let mut out = Vec::new();
    let mut x = 0i64;
    let mut y = 0i64;
    for cmd in v["commands"].as_array().unwrap() {
        let dx = cmd[0].as_i64().unwrap_or(0);
        let dy = cmd[1].as_i64().unwrap_or(0);
        let flags = cmd[2].as_i64().unwrap();
        let t = match flags {
            8 => StitchType::End,
            4 => StitchType::ColorChange,
            f if f & 0b11 != 0 => StitchType::Jump,
            _ => StitchType::Stitch,
        };
        x += dx;
        y += dy;
        out.push((x as i32, y as i32, t));
    }
    out
}

fn check_file(name: &str) {
    let raw_expected_path = fixture_dir().join("raw_expected.json");
    let all: Value =
        serde_json::from_str(&std::fs::read_to_string(raw_expected_path).unwrap()).unwrap();

    let bytes = std::fs::read(fixture_dir().join(name)).unwrap();
    let parsed = parse_pes(&bytes);
    assert!(parsed.is_ok(), "falha ao parsear {name}: {:?}", parsed.err());

    let pattern = parsed.unwrap();
    let ours: Vec<(f32, f32, StitchType)> = pattern
        .stitches
        .iter()
        .map(|s| (s.x, s.y, s.stitch_type))
        .collect();

    let theirs: Vec<(f32, f32, StitchType)> = reference_commands(&all[name])
        .into_iter()
        .map(|(x, y, t)| (x as f32, y as f32, t))
        .collect();

    // Our parser emits End before running out of data; reference may have
    // more trailing garbage-after-end commands. Compare only up to our End.
    let cmp_len = ours.len().min(theirs.len());
    assert!(
        ours.len() >= theirs.len() - 2,
        "{name}: nosso parser parou cedo demais ({} vs {})",
        ours.len(),
        theirs.len()
    );
    assert_eq!(&ours[..cmp_len], &theirs[..cmp_len], "{name}: stream diverge");
}

#[test]
fn pes_golden_simple() {
    check_file("simple.pes");
}

#[test]
fn pes_golden_longform() {
    check_file("longform.pes");
}

#[test]
fn pes_golden_multicolor() {
    check_file("multicolor.pes");
}

